sudo: false
language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - 7.1
  - nightly
  - hhvm
matrix:
  allow_failures:
    - php: hhvm
    - php: nightly
before_script:
  - composer install --no-interaction
